<li class="item comment-form">
	<div class="post-title">
		<h2>SUBMIT COMMENT</h2>
		
	</div>
	
	<form action="<?php echo $this->getPostCommentUrl() ?>" method="post" id="comment-form">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="content">
			<ul class="form-list">
				<li>
					<label for="comment-name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
					<div class="input-box">
						<input type="input" name="comment[name]" class="input-text required-entry" id="comment-name" title="<?php echo $this->__('Name') ?>" />
					</div>
				</li>
			
				<li>
					<label for="comment-email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
					<div class="input-box">
						<input type="text" name="comment[email]" value="" id="comment-email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email') ?>" />
					</div>
				</li>
				<li>
					<label for="comment-content" class="required"><em>*</em><?php echo $this->__('Comment') ?></label>
					<div class="input-box">
						<textarea name="comment[content]" class="input-text required-entry" id="comment-content" title="<?php echo $this->__('Comment') ?>" ></textarea>
					</div>
				</li>
			</ul>
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			
			<div class="buttons-set">
				<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<input type="hidden" id="comment-post_id" name="comment[post_id]" value="<?php echo $this->getPostId();?>"/>
			</div>			
		</div>	
    </form>
	
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('comment-form', true);
    //]]>
    </script>

</li>
